### ISSUE TITLE
升级依赖库报错

### ISSUE THREAD

**Issue by Esword618** [wangluozhe/requests#1]
```
 go get github.com/wangluozhe/requests@v1.0.02
# github.com/wangluozhe/requests/utils
..\..\pkg\mod\github.com\wangluozhe\requests@v1.0.1-0.20220326140523-ddfad66c7dd3\utils\code.go:21:12: undefined: stringAndByte
..\..\pkg\mod\github.com\wangluozhe\requests@v1.0.1-0.20220326140523-ddfad66c7dd3\utils\code.go:27:12: undefined: stringAndByte
..\..\pkg\mod\github.com\wangluozhe\requests@v1.0.1-0.20220326140523-ddfad66c7dd3\utils\code.go:33:12: undefined: stringAndByte
..\..\pkg\mod\github.com\wangluozhe\requests@v1.0.1-0.20220326140523-ddfad66c7dd3\utils\code.go:43:12: undefined: stringAndByte
```
上面是报错信息

**Comment by wangluozhe** [comment]
> ```
>  go get github.com/wangluozhe/requests@v1.0.02
> # github.com/wangluozhe/requests/utils
> ..\..\pkg\mod\github.com\wangluozhe\requests@v1.0.1-0.20220326140523-ddfad66c7dd3\utils\code.go:21:12: undefined: stringAndByte
> ..\..\pkg\mod\github.com\wangluozhe\requests@v1.0.1-0.20220326140523-ddfad66c7dd3\utils\code.go:27:12: undefined: stringAndByte
> ..\..\pkg\mod\github.com\wangluozhe\requests@v1.0.1-0.20220326140523-ddfad66c7dd3\utils\code.go:33:12: undefined: stringAndByte
> ..\..\pkg\mod\github.com\wangluozhe\requests@v1.0.1-0.20220326140523-ddfad66c7dd3\utils\code.go:43:12: undefined: stringAndByte
> ```
> 
> 上面是报错信息
这个我刚刚修复了，把依赖库删除后在重新go get github.com/wangluozhe/requests@v1.0.02

**Comment by Esword618** [comment]
好的，感谢！
