### ISSUE TITLE
大佬麻烦问问如果我请求不想通过gzip压缩怎么设置呢

### ISSUE THREAD

**Issue by fxhj3210** [wangluozhe/requests#11]
大佬麻烦问问如果我请求不想通过gzip压缩怎么设置呢,
我试了
req.Headers.Set("Accept-Encoding", "identity")
和
req.Headers.Set("Accept-Encoding", "")
都没用,请求发出去的时候依旧编码

**Comment by wangluozhe** [comment]
这个是因为老版本的fhttp导致的，你更新一下fhttp就行，更新命令：go get github.com/Danny-Dasilva/fhttp，我在下个版本也会更新
