### ISSUE TITLE
内存泄漏,已定位原因

### ISSUE THREAD

**Issue by fxhj3210** [wangluozhe/requests#14]
调用每次请求都是短链接，但是使用了连接池(Transport)的配置，而且没有指定连接空闲断开时间(Transport.IdleConnTimeout)，也没有禁用长连接(设置 Transport.DisableKeepAlives = true)，导致连接变成了长连接，对方服务端不主动断开的话，连接会一直存在。

整改方案:设置
Transport.DisableKeepAlives

**Comment by wangluozhe** [comment]
好的，多谢提醒，我会抽空改进，多谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月18日(周日) 晚上9:32
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [wangluozhe/requests] 内存泄漏,已定位原因 (Issue #14)




 
调用每次请求都是短链接，但是使用了连接池(Transport)的配置，而且没有指定连接空闲断开时间(Transport.IdleConnTimeout)，也没有禁用长连接(设置 Transport.DisableKeepAlives = true)，导致连接变成了长连接，对方服务端不主动断开的话，连接会一直存在。
 
整改方案:设置
 Transport.DisableKeepAlives

**Comment by wangluozhe** [comment]
你也可以加我微信，跟我一起完善这个项目，我的微信号：wx1670044143



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月18日(周日) 晚上9:32
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [wangluozhe/requests] 内存泄漏,已定位原因 (Issue #14)




 
调用每次请求都是短链接，但是使用了连接池(Transport)的配置，而且没有指定连接空闲断开时间(Transport.IdleConnTimeout)，也没有禁用长连接(设置 Transport.DisableKeepAlives = true)，导致连接变成了长连接，对方服务端不主动断开的话，连接会一直存在。
 
整改方案:设置
 Transport.DisableKeepAlives
