### ISSUE TITLE
错误的预处理逻辑导致url被重复编码,访问失败

### ISSUE THREAD

**Issue by fxhj3210** [wangluozhe/requests#16]
上级返回我们的链接
https://payplf-gate.yy.com/ch/front/weixin-wap2.do?data=https%3A%2F%2Fwx.tenpay.com%2Fcgi-bin%2Fmmpayweb-bin%2Fcheckmweb%3Fprepay_id%3Dwx20111508629760e1bbf681a3b9a8760000%26package%3D2701796942%26redirect_url%3Dhttps%3A%2F%2Fpayplf-gate.yy.com%2Fch%2Freturn%2Fweixin%2Fwap2%2F1302022102012386907312.do
我们此时需要直接访问该链接,于是建立了get请求
但是
url经过内部处理后,实际访问链接变成了
https://payplf-gate.yy.com/ch/front/weixin-wap2.do?data=https%253A%252F%252Fwx.tenpay.com%252Fcgi-bin%252Fmmpayweb-bin%252Fcheckmweb%253Fprepay_id%253Dwx20111508629760e1bbf681a3b9a8760000%2526package%253D2701796942%2526redirect_url%253Dhttps%253A%252F%252Fpayplf-gate.yy.com%252Fch%252Freturn%252Fweixin%252Fwap2%252F1302022102012386907312.do
被重复编码了.
折磨了一通宵,眼睛都看瞎了才发现被重复编码了,
经查,就是在预处理那发生的bug,导致访问链接直接变了

**Comment by fxhj3210** [comment]
那如果我们先解码,然后再进内部处理可否正常呢
尝试了,直接变成
https://payplf-gate.yy.com/ch/front/weixin-wap2.do?package=880750705&redirect_url=https%3A%2F%2Fpayplf-gate.yy.com%2Fch%2Freturn%2Fweixin%2Fwap2%2F1302022102012386942549.do 
丢参数了

**Comment by fxhj3210** [comment]
所以我建议编码应当由用户处理,而不应当由程序内部处理

**Comment by fxhj3210** [comment]
定位到问题了
`// 预处理url
func (pr *PrepareRequest) Prepare_url(rawurl string, params *url.Params) error {
	rawurl = strings.TrimSpace(rawurl)
	urls, err := url.Parse(rawurl)
	if err != nil {
		return err
	}
	if urls.Scheme == "" {
		return errors.New(fmt.Sprintf("Invalid URL %s: No scheme supplied. Perhaps you meant http://%s?", rawurl, rawurl))
	} else if urls.Host == "" {
		return errors.New(fmt.Sprintf("Invalid URL %s: No host supplied", rawurl))
	}
	if urls.Path == "" {
		urls.Path = "/"
	}
	if params != nil {
		if urls.RawParams != "" {
			urls.Params = url.ParseParams(urls.RawParams + "&" + params.Encode())
		} else {
			urls.Params = url.ParseParams(params.Encode())//被第一次编码
		}
	}
	pr.Url = urls.String()//被第二次编码
	return nil
}
`

**Comment by wangluozhe** [comment]
> 定位到问题了
> 
> ```
> // 预处理url
> func (pr *PrepareRequest) Prepare_url(rawurl string, params *url.Params) error {
> 	rawurl = strings.TrimSpace(rawurl)
> 	urls, err := url.Parse(rawurl)
> 	if err != nil {
> 		return err
> 	}
> 	if urls.Scheme == "" {
> 		return errors.New(fmt.Sprintf("Invalid URL %s: No scheme supplied. Perhaps you meant http://%s?", rawurl, rawurl))
> 	} else if urls.Host == "" {
> 		return errors.New(fmt.Sprintf("Invalid URL %s: No host supplied", rawurl))
> 	}
> 	if urls.Path == "" {
> 		urls.Path = "/"
> 	}
> 	if params != nil {
> 		if urls.RawParams != "" {
> 			urls.Params = url.ParseParams(urls.RawParams + "&" + params.Encode())
> 		} else {
> 			urls.Params = url.ParseParams(params.Encode())//被第一次编码
> 		}
> 	}
> 	pr.Url = urls.String()//被第二次编码
> 	return nil
> }
> ```

感谢提醒，我和尽快修复然后更新版本的

**Comment by wangluozhe** [comment]
> 

请你使用utils.DecodeURIComponent函数转换一下，因为我需要保留这种情况的。可能其他网站就是需要二次编码，所以我不能主动解码，请自行解码一下。
