### ISSUE TITLE
访问带有%号的目录会报错 例如http://www.baidu.com/1.%EXT%

### ISSUE THREAD

**Issue by Pik-sec** [wangluozhe/requests#18]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x104c8ac78]

**Comment by wangluozhe** [comment]
> panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x104c8ac78]

已经解决此错误，感谢反馈。
