### ISSUE TITLE
Session设置Ja3后 第二次发送请求报 tls: CurvePreferences includes unsupported curve.

### ISSUE THREAD

**Issue by AceRogue** [wangluozhe/requests#2]
Session设置Ja3后 第二次发送请求报 tls: CurvePreferences includes unsupported curve.

**Comment by wangluozhe** [comment]
有没有复现代码，我试试看

**Comment by wangluozhe** [comment]
> Session设置Ja3后 第二次发送请求报 tls: CurvePreferences includes unsupported curve.

有没有复现代码，发我，我试试看看

**Comment by AceRogue** [comment]
`func main() {
	session := requests.NewSession()
	session.Ja3 = "771,4865-4866-4867-49195-49199-49196-49200-52393-52392-49171-49172-156-157-47-53,0-23-65281-10-11-35-16-5-13-18-51-45-43-27-21,29-23-24,0"

	for i := 0; i < 2; i++ {
		req := url.NewRequest()
		headers := url.NewHeaders()
		headers.Set("User-Agent", "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36")
		req.Headers = headers
		r, err := session.Get("https://ja3er.com/json", req)
		if err != nil {
			fmt.Println(err)
		}
		fmt.Println(r.Text)
	}
}`
本地执行后报错
`
{"ja3_hash":"b32309a26951912be7dba376398abc3b", "ja3": "771,4865-4866-4867-49195-49199-49196-49200-52393-52392-49171-49172-156-157-47-53,0-23-65281-10-11-35-16-5-13-18-51-45-43-27-21,29-23-24,0", "User-Agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36"}
Get "https://ja3er.com/json": tls: CurvePreferences includes unsupported curve
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x30 pc=0x1047a0e98]
`

**Comment by Digman** [comment]
这个能修复吗？

**Comment by wangluozhe** [comment]
> 这个能修复吗？

稍安勿躁，先暂时别使用session功能，直接使用requests.Get(url,req)，在req里面设置ja3，这个问题估计得我有空后修复一波。

**Comment by wangluozhe** [comment]
> ```
>     func main() {
>         session := requests.NewSession()
>         session.Ja3 = "771,4865-4866-4867-49195-49199-49196-49200-52393-52392-49171-49172-156-157-47-53,0-23-65281-10-11-35-16-5-13-18-51-45-43-27-21,29-23-24,0"
> 
>         for i := 0; i < 2; i++ {
>             req := url.NewRequest()
>             headers := url.NewHeaders()
>             headers.Set("User-Agent", "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36")
>             req.Headers = headers
>             r, err := session.Get("https://ja3er.com/json", req)
>             if err != nil {
>                 fmt.Println(err)
>             }
>             fmt.Println(r.Text)
>         }
>     }
> ```
> 
> 本地执行后报错
> 
> ```
> {"ja3_hash":"b32309a26951912be7dba376398abc3b", "ja3": "771,4865-4866-4867-49195-49199-49196-49200-52393-52392-49171-49172-156-157-47-53,0-23-65281-10-11-35-16-5-13-18-51-45-43-27-21,29-23-24,0", "User-Agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36"} 
> Get "https://ja3er.com/json": tls: CurvePreferences includes unsupported curve panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x2 addr=0x30 pc=0x1047a0e98]
> ```

稍安勿躁，先暂时别使用session功能，直接使用requests.Get(url,req)，在req里面设置ja3，这个问题估计得我有空后修复一波。

**Comment by Digman** [comment]
貌似是重复调用`this.transport.TLSClientConfig`的原因

**Comment by wangluozhe** [comment]
> 貌似是重复调用`this.transport.TLSClientConfig`的原因

感谢你给的建议，正是这个原因，现在已经修复了，我马上上新版本，你就可以用了

**Comment by wangluozhe** [comment]
> Session设置Ja3后 第二次发送请求报 tls: CurvePreferences includes unsupported curve.

已修复，代码无需改变，请更新到v1.0.2版本即可。

**Comment by AceRogue** [comment]
感谢大佬！
