### ISSUE TITLE
链接中有中文，被urlencode了两次

### ISSUE THREAD

**Issue by amobaishi** [wangluozhe/requests#38]
链接中有中文，被urlencode了两次，例如 链接中有 “全部”  ，请求的时候，被转码两次 变成 “%25E5%2585%25A8%25E9%2583%25A8”，导致请求失败，如果先将 “全部” 编码为“%E5%85%A8%E9%83%A8”，请求会变成“%2525E5%252585%2525A8%2525E9%252583%2525A8” 又被转码了两次

**Comment by wangluozhe** [comment]
已更新，将requests更新为1.1.15版本即可。
