### ISSUE TITLE
CurvePreferences includes unsupported curve

### ISSUE THREAD

**Issue by dunaevv** [wangluozhe/requests#6]
Have the following error:

```
Get "https://www.costco.com.mx/": tls: CurvePreferences includes unsupported curve
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x6fc110]

goroutine 1 [running]:
main.main()
        /home/sonyboy/go/src/github/sonyboy/fetch/main.go:27 +0x1d0
exit status 2
```

**Comment by wangluozhe** [comment]
> Have the following error:
> 
> ```
> Get "https://www.costco.com.mx/": tls: CurvePreferences includes unsupported curve
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x6fc110]
> 
> goroutine 1 [running]:
> main.main()
>         /home/sonyboy/go/src/github/sonyboy/fetch/main.go:27 +0x1d0
> exit status 2
> ```

Please send me the duplicate code and I will test it

**Comment by dunaevv** [comment]
> Sure, here we go:

```
package main

import (
	"fmt"

	"github.com/wangluozhe/requests"
	"github.com/wangluozhe/requests/url"
)

func checkErr(err error) {
	if err != nil {
		panic(err)
	}
}

func main() {

	req := url.NewRequest()
	headers := url.NewHeaders()
	headers.Set("User-Agent", "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36")
	req.Headers = headers
	req.Ja3 = "771,4865-4866-4867-49195-49199-49196-49200-52393-52392-49171-49172-156-157-47-53,0-23-65281-10-11-35-16-5-13-18-51-45-43-27-21,29-23-24,0"
	r, err := requests.Get("https://www.costco.com.mx/", req)
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println(r.Text)

}
```
Thx in advance!

**Comment by dunaevv** [comment]
> > Have the following error:
> > ```
> > Get "https://www.costco.com.mx/": tls: CurvePreferences includes unsupported curve
> > panic: runtime error: invalid memory address or nil pointer dereference
> > [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x6fc110]
> > 
> > goroutine 1 [running]:
> > main.main()
> >         /home/sonyboy/go/src/github/sonyboy/fetch/main.go:27 +0x1d0
> > exit status 2
> > ```
> 
> Please send me the duplicate code and I will test it

I think I know, why It`s was error, I change Ja3 and now It`s ok
from: "769,255-49188-49187-49162-49161-49160-49192-49191-49172-49171-49170-49190-49189-49157-49156-49155-49194-49193-49167-49166-49165-107-103-57-51-22-61-60-53-47-10-49159-49169-49154-49164-5-4,0-10-11-13,23-24-25,0"
to : "769,255-49196-49195-49188-49187-49162-49161-49160-49200-49199-49192-49191-49172-49171-49170-157-156-61-60-53-47-10,35-0-10-11-13,23-24-25,0"

**Comment by wangluozhe** [comment]
> > > Have the following error:
> > > ```
> > > Get "https://www.costco.com.mx/": tls: CurvePreferences includes unsupported curve
> > > panic: runtime error: invalid memory address or nil pointer dereference
> > > [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x6fc110]
> > > 
> > > goroutine 1 [running]:
> > > main.main()
> > >         /home/sonyboy/go/src/github/sonyboy/fetch/main.go:27 +0x1d0
> > > exit status 2
> > > ```
> > 
> > 
> > Please send me the duplicate code and I will test it
> 
> I think I know, why It`s was error, I change Ja3 and now It`s ok from: "769,255-49188-49187-49162-49161-49160-49192-49191-49172-49171-49170-49190-49189-49157-49156-49155-49194-49193-49167-49166-49165-107-103-57-51-22-61-60-53-47-10-49159-49169-49154-49164-5-4,0-10-11-13,23-24-25,0" to : "769,255-49196-49195-49188-49187-49162-49161-49160-49200-49199-49192-49191-49172-49171-49170-157-156-61-60-53-47-10,35-0-10-11-13,23-24-25,0"

You try the latest version
