### ISSUE TITLE
 uTlsConn.Handshake() error

### ISSUE THREAD

**Issue by dunaevv** [wangluozhe/requests#8]
I have the following error =>

`func main() {
	req := url.NewRequest()
	headers := url.NewHeaders()
	headers.Set("User-Agent", "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36")
	req.Headers = headers
	req.Ja3 = "772,4865-4866-4867-49195-49199-49196-49200-52393-52392-49171-49172-156-157-47-53,0-23-65281-10-11-35-16-5-13-18-51-45-43-27-21,29-23-24,"
	r, err := requests.Get("https://www.bet365.nl/#/HO/", req)
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println(r.Text)
}

>> Get "https://www.bet365.nl/": uTlsConn.Handshake() error: local error: tls: unexpected message
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x6eeb30]

goroutine 1 [running]:
main.main()
        /home/sonyboy/go/src/github/dunaevv/bookmaker_app/main.go:20 +0x1d0
exit status 2`

**Comment by gbe3hunna** [comment]
Same Handshake Error with:

UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
JA3: 771,4865-4866-4867-49195-49199-49196-49200-52393-52392-49171-49172-156-157-47-53,0-23-65281-10-11-35-16-5-13-18-51-45-43-27-17513,29-23-24,0
JA3 HASH: e1d8b04eeb8ef3954ec4f49267a783ef
